
# please randomize this when first configureing this deployment
# run this on a shell to create the the random
# python3 -c 'import os; print(os.urandom(16).hex())'
# place output in FLASK_JWT_SECRET_KEY
# changing this number efectively revokes all active tokens
FLASK_JWT_SECRET_KEY: "edaaedb41f31d8141bb3e8ae6e261ec8"


####################################
########## Dev settings ############
####################################

# flask debug mode
FLASK_DEBUG: false


####################################
##### no need to change below ######
####################################

# OPE parameters

# key length
ORE_KEY_LENGTH: 256

# input is 0 - (2^64 -1)
OPE_IN_MIN: 0
OPE_IN_MAX: 18446744073709551615

# output is 0 - (2^128 -1)
OPE_OUT_MIN: 0
OPE_OUT_MAX: 340282366920938463463374607431768211455


# where is the kms backend db
backed_DB_uri: "mongodb://priv-kms-db:27017/"

# db name and coll names
db_name: KMS_db
attrib_col_name: attributes
users_col_name: Users

# internal to this container
DE_key_location: "/secrets/DE_key.pem" 
ORE_key_location: "/secrets/ORE_key.bin"